name: Build NAStoolOCR Image
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/build.yml
      - requirements.txt
jobs:
  build:
    runs-on: ubuntu-latest
    name: mmm
    steps:
      -
        name: Checkout
        uses: actions/checkout@master

      -
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      -
        name: Buildx
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/arm64
          push: true
          tags: mimimimimimimiiii/ocr:latest
